#app
server:
  port: 8080
spring:
  datasource:
    dynamic:
      primary: test #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        test:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.8:3306/test?serverTimezone=Hongkong&serverTimezone=GMT%2b8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false
          username: root
          password: '123456'
  shardingsphere:
    datasource:
      names: test0,test1,test2
      test0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.8:3306/test0?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false
        username: root
        password: '123456'
      test1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.8:3306/test1?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false
        username: root
        password: '123456'
      test2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.8:3306/test2?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false
        username: root
        password: '123456'
    rules:
      sharding:
        tables:
          user:
            actual-data-nodes: test$->{0..2}.user_$->{0..2}
            database-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: test-inline
            tableStrategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: user-inline
        sharding-algorithms:
          test-inline:
            type: inline
            props:
              algorithm-expression: test$->{id % 3}
          user-inline:
            type: inline
            props:
              algorithm-expression: user_$->{id % 3}
    props:
      sql-show: true # 日志显示SQL
mydoc:
  enable: true

logging:
  level:
    com:
      enjoy7: debug

mybatis-plus:
  #  mapper-locations: classpath:mapper/*/*.xml
  #  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.enjoy7.test.user.system.mapper
  #  global-config:
  #    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  #    id-type: 0
  #    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  #    field-strategy: 2
  #    #驼峰下划线转换
  #    db-column-underline: false
  #    #刷新mapper 调试神器
  #    refresh-mapper: true
  #    #数据库大写下划线转换
  #    #capital-mode: true
  #    #序列接口实现类配置
  #    #key-generator: com.baomidou.springboot.xxx
  #    #逻辑删除配置
  #    logic-delete-value: 0
  #    logic-not-delete-value: 1
  #    #自定义填充策略接口实现
  #    #meta-object-handler: com.baomidou.springboot.xxx
  #    #自定义SQL注入器
  #    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    call-setters-on-nulls: true



#manage:
#  url: http://testybg.enjoy7.com/new-order/
#confirmHarvest:
#  url: https://testdistributionapi.enjoy7.com/manage/confirmHarvest
#weixin:
#  notifyUrl: https://testdistributionapi.enjoy7.com/applets/xcxNotify