#app
server:
  servlet:
    context-path: /
#spring
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    additional-paths: src/main/java
    exclude: /static/**,/public/**
  thymeleaf:
    cache: false

  resources:
    static-locations: classpath:static/,file:static/
  servlet:
    #converters:
    #  preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

logging:
  pattern:
    #      console: "%n%-5level, %d{yyyy-MM-dd HH:mm:ss.SSS}, [%t], - %m%n %caller"
    console: "%-5level, %d{yyyy-MM-dd HH:mm:ss.SSS}, [%t], - %m%n"
